//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEACHER.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGVEntities : DbContext
    {
        public QLGVEntities()
            : base("name=QLGVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donvi_tolamviec_junction> Donvi_tolamviec_junction { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBangcap> tblBangcaps { get; set; }
        public virtual DbSet<tblChucvu> tblChucvus { get; set; }
        public virtual DbSet<tblDantoc> tblDantocs { get; set; }
        public virtual DbSet<tblDSDonvi> tblDSDonvis { get; set; }
        public virtual DbSet<tblHopdong> tblHopdongs { get; set; }
        public virtual DbSet<tblNgoaingu> tblNgoaingus { get; set; }
        public virtual DbSet<tblNguoidung> tblNguoidungs { get; set; }
        public virtual DbSet<tblNhanvien> tblNhanviens { get; set; }
        public virtual DbSet<tblTinhoc> tblTinhocs { get; set; }
        public virtual DbSet<tblTolamviec> tblTolamviecs { get; set; }
        public virtual DbSet<tblTongiao> tblTongiaos { get; set; }
    }
}
