//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEACHER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHopdong
    {
        public string Mahopdong { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public Nullable<int> Lanky { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> Ngayky { get; set; }
        public string Tennguoiky { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tblNhanvien tblNhanvien { get; set; }
    }
}
