//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEACHER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanvien()
        {
            this.tblHopdongs = new HashSet<tblHopdong>();
        }
    
        public int Manv { get; set; }
        public string TenNV { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
        public string Tinhthanh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string Nguyenquan { get; set; }
        public string Dctamtru { get; set; }
        public string Email { get; set; }
        public string SDTrieng { get; set; }
        public string SDTnha { get; set; }
        public string Tinhtranghonnhan { get; set; }
        public string Tinhtranglamviec { get; set; }
        public string MaDV { get; set; }
        public string Mato { get; set; }
        public string Machucvu { get; set; }
        public Nullable<System.DateTime> Ngayvaolam { get; set; }
        public Nullable<int> Thamnien { get; set; }
        public string Matinhoc { get; set; }
        public string Mangoaingu { get; set; }
        public string Mabangcap { get; set; }
        public string SoBHXH { get; set; }
        public string SoBHYT { get; set; }
        public string Matongiao { get; set; }
        public string Madantoc { get; set; }
    
        public virtual tblBangcap tblBangcap { get; set; }
        public virtual tblChucvu tblChucvu { get; set; }
        public virtual tblDantoc tblDantoc { get; set; }
        public virtual tblDantoc tblDantoc1 { get; set; }
        public virtual tblDSDonvi tblDSDonvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHopdong> tblHopdongs { get; set; }
        public virtual tblNgoaingu tblNgoaingu { get; set; }
        public virtual tblTinhoc tblTinhoc { get; set; }
        public virtual tblTolamviec tblTolamviec { get; set; }
        public virtual tblTongiao tblTongiao { get; set; }
        public virtual tblTongiao tblTongiao1 { get; set; }
    }
}
