//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEACHER.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTolamviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTolamviec()
        {
            this.Donvi_tolamviec_junction = new HashSet<Donvi_tolamviec_junction>();
        }
    
        public string Mato { get; set; }
        public string Tento { get; set; }
        public string Ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donvi_tolamviec_junction> Donvi_tolamviec_junction { get; set; }
    }
}
